### ISSUE TITLE
Looks like the calculations are off

### ISSUE THREAD

**Issue by jamiehewitt15** [kremalicious/asi-calculator#34]
It should be:

```
40000 * 0.433226 = 17329.04
```

Instead, it looks like 40000 Ocean = 20000 ASI

![image](https://github.com/user-attachments/assets/31c31986-90d8-48fb-9ebd-ccd90c6a4a88)

**Comment by kremalicious** [comment]
thanks for noticing! Have pinpointed it to the number formatting library as calculation in background seem to be correct. But display values are rounded up generously for whatever reason
